# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildarmv7:
    name: buildarmv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.0.6
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 7.0.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install newgrounds 1.2.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-tools 1.4.4 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -D no-compilation -D no_debug -D luajit_static -D macro-times -D analyzer-optimize -armv7 --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: buildarmv7
          path: export/release/android/bin/app/build/outputs/apk/debug

  buildarm64:
    name: buildarm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.0.6
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 7.0.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install newgrounds 1.2.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-tools 1.4.4 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -D no-compilation -D no_debug -D luajit_static -D macro-times -D analyzer-optimize -arm64 --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: buildarm64
          path: export/release/android/bin/app/build/outputs/apk/debug
  build86:
    name: build86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.0.6
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 7.0.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install newgrounds 1.2.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-tools 1.4.4 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -D no-compilation -D no_debug -D luajit_static -D macro-times -D analyzer-optimize -32 --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build86
          path: export/release/android/bin/app/build/outputs/apk/debug
