# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build32:
    name: build32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp 4.2.1 > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 7.0.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install newgrounds 1.1.4 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-tools 1.4.4 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -32 -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build32
          path: export/release/windows/bin
  build64:
    name: build64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp 4.2.1 > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 7.0.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install newgrounds 1.1.5 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-tools 1.4.4 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -64 -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build64
          path: export/release/windows/bin
