# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build32:
    name: build32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.8.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib git openfl https://github.com/mcagabe19/fastfl-9.0.2.git
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib git newgrounds https://github.com/Geokureli/Newgrounds.git
          haxelib install actuate 1.8.7 --quiet
          haxelib install box2d 1.2.2 --quiet
          haxelib install layout 1.2.0 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.8.1 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.2 --quiet
          haxelib install hscript 2.3.0 --quiet
          haxelib install flixel-addons 2.8.0 --quiet
          haxelib install flixel-demos 2.7.2 --quiet
          haxelib install flixel-templates 2.6.4 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -32 --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build32
          path: export/release/windows/bin
  build64:
    name: build64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.8.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib git openfl https://github.com/mcagabe19/fastfl-9.0.2.git
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib git newgrounds https://github.com/Geokureli/Newgrounds.git
          haxelib install actuate 1.8.7 --quiet
          haxelib install box2d 1.2.2 --quiet
          haxelib install layout 1.2.0 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib --never install flixel 4.8.1 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.2 --quiet
          haxelib install hscript 2.3.0 --quiet
          haxelib install flixel-addons 2.8.0 --quiet
          haxelib install flixel-demos 2.7.2 --quiet
          haxelib install flixel-templates 2.6.4 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -64 --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build64
          path: export/release/windows/bin
