# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build19-32:
    name: Windows Server 2019 (32)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples --quiet
          haxelib install newgrounds --quiet
          haxelib install actuate --quiet
          haxelib install box2d --quiet
          haxelib install layout --quiet
          haxelib install systools --quiet
          haxelib --never install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-demos --quiet
          haxelib install flixel-templates --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -32 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build19-32
          path: export/release/windows/bin
  build19-64:
    name: Windows Server 2019 (64)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples --quiet
          haxelib install newgrounds --quiet
          haxelib install actuate --quiet
          haxelib install box2d --quiet
          haxelib install layout --quiet
          haxelib install systools --quiet
          haxelib --never install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-demos --quiet
          haxelib install flixel-templates --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -64 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build19-64
          path: export/release/windows/bin
  build22-32:
    name: Windows Server 2022 (32)
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples --quiet
          haxelib install newgrounds --quiet
          haxelib install actuate --quiet
          haxelib install box2d --quiet
          haxelib install layout --quiet
          haxelib install systools --quiet
          haxelib --never install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-demos --quiet
          haxelib install flixel-templates --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -32 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build22-32
          path: export/release/windows/bin
  build22-64:
    name: Windows Server 2022 (64)
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples --quiet
          haxelib install newgrounds --quiet
          haxelib install actuate --quiet
          haxelib install box2d --quiet
          haxelib install layout --quiet
          haxelib install systools --quiet
          haxelib --never install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-demos --quiet
          haxelib install flixel-templates --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -64 -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build22-64
          path: export/release/windows/bin
